// This file will be auto-generated by Supabase
// Run: npm run types:generate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Generated types will appear here
    }
  }
}
